&ANALYZE-SUSPEND _EXPORT-NUMBER AB_v10r12
&ANALYZE-RESUME
FORM 
    Incidencias.CATUsuarioCAT.NombreUsuarioCAT AT ROW 4 COL 24 COLON-ALIGNED
    Incidencias.CATUsuarioCAT.AMaterno COLON 24
    Incidencias.CATUsuarioCAT.APaterno COLON 24
    Incidencias.CATUsuarioCAT.CiscoUsuario AT ROW 4 COL 33 COLON-ALIGNED
    Incidencias.CATUsuarioCAT.EmailUsuario COLON 33
  WITH SIDE-LABELS SCROLLABLE THREE-D.
ENABLE ALL.
